language: python
sudo: false
python:
  - "2.7"
services:
  - redis-server
env:
  - TOXENV=py2.7-django1.7
install:
  - pip install -q --use-mirrors tox
before_script:
  - createdb -E UTF-8 dash -U postgres -O $USER
script:
  - tox -- --settings=dash_test_runner.settings_travis
